name: 'Get & Cach dependencies'
description: 'Get the dependencies and cache them'
inputs:
  caching:
    description: 'whether or not you want caching to happen'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'whether the cache was used or not'
    value: ${{steps.install.outputs.cache}}
runs:
  using: 'composite'
  steps:
    - name: print output to ensure we're using this action
      run: echo "custom action was used"
      shell: bash
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == false
      run: |
        npm ci
        echo "::set-output name=cache::${{inputs.caching}}"
      shell: bash
